[data]
cleaned = "data/cleaned"
extended = "data/extended"
prepared = "data/prepared"

[data.sources]
instagram = "/mnt/barracuda/social_media_dumps/instagram_dave_holds_himself_accountable"
weights = "/mnt/barracuda/data/weights.ods"

[clean.out]
instagram_posts = "data/cleaned/posts.csv"
instagram_pictures = "data/cleaned/pictures.csv"
weights = "data/cleaned/weights.csv"

[extended]
meals = "data/extended/meals.csv"
meals_posts = "data/extended/meals_posts.csv"

[extend]
meal_range_minutes = 60

[prepare.out]
sqlite = "data/prepared/data.db"
