[sources]
instagram = "/mnt/barracuda/social_media_dumps/instagram_dave_holds_himself_accountable"
weights = "/mnt/barracuda/data/weights.ods"

[cleaned]
instagram_posts = "data/cleaned/posts.csv"
instagram_pictures = "data/cleaned/pictures.csv"
weights = "data/cleaned/weights.csv"

[extended]
meals = "data/extended/meals.csv"
meals_posts = "data/extended/meals_posts.csv"
interpolated_weights = "data/extended/interpolated_weights.csv"

[extend]
meal_range_minutes = 60
avg_weight_window = 14

[prepared]
sqlite = "data/prepared/data.db"

[prepare]
sql = "src/prepare/sql"
